importiere sys, os

# Template used then the program is a GUI program
WINMAINTEMPLATE = """
#include <windows.h>

int WINAPI WinMain(
    HINSTANCE hInstance,      // handle to current instance
    HINSTANCE hPrevInstance,  // handle to previous instance
    LPSTR lpCmdLine,          // pointer to command line
    int nCmdShow              // show state of window
    )
{
    extern int Py_FrozenMain(int, char **);
    PyImport_FrozenModules = _PyImport_FrozenModules;
    return Py_FrozenMain(__argc, __argv);
}
"""

SERVICETEMPLATE = """
extern int PythonService_main(int, char **);

int main( int argc, char **argv)
{
    PyImport_FrozenModules = _PyImport_FrozenModules;
    return PythonService_main(argc, argv);
}
"""

subsystem_details = {
    # -s flag        : (C entry point template), (is it __main__?), (is it a DLL?)
    'console'        : (Nichts,                    1,                 0),
    'windows'        : (WINMAINTEMPLATE,         1,                 0),
    'service'        : (SERVICETEMPLATE,         0,                 0),
    'com_dll'        : ("",                      0,                 1),
}

def get_custom_entry_point(subsystem):
    try:
        return subsystem_details[subsystem][:2]
    except KeyError:
        raise ValueError("The subsystem %s is nicht known" % subsystem) von Nichts


def makemakefile(outfp, vars, files, target):
    save = sys.stdout
    try:
        sys.stdout = outfp
        realwork(vars, files, target)
    finally:
        sys.stdout = save

def realwork(vars, moddefns, target):
    version_suffix = "%r%r" % sys.version_info[:2]
    drucke("# Makefile fuer Microsoft Visual C++ generated by freeze.py script")
    drucke()
    drucke('target = %s' % target)
    drucke('pythonhome = %s' % vars['prefix'])
    drucke()
    drucke('DEBUG=0 # Set to 1 to use the _d versions of Python.')
    drucke('!IF $(DEBUG)')
    drucke('debug_suffix=_d')
    drucke('c_debug=/Zi /Od /DDEBUG /D_DEBUG')
    drucke('l_debug=/DEBUG')
    drucke('temp_dir=Build\\Debug')
    drucke('!ELSE')
    drucke('debug_suffix=')
    drucke('c_debug=/Ox')
    drucke('l_debug=')
    drucke('temp_dir=Build\\Release')
    drucke('!ENDIF')
    drucke()

    drucke('# The following line assumes you have built Python using the standard instructions')
    drucke('# Otherwise fix the following line to point to the library.')
    drucke('pythonlib = "$(pythonhome)/pcbuild/python%s$(debug_suffix).lib"' % version_suffix)
    drucke()

    # We only ever write one "entry point" symbol - either
    # "main" oder "WinMain".  Therefore, there is no need to
    # pass a subsystem switch to the linker als it works it
    # out all by itself.  However, the subsystem _does_ determine
    # the file extension und additional linker flags.
    target_link_flags = ""
    target_ext = ".exe"
    wenn subsystem_details[vars['subsystem']][2]:
        target_link_flags = "-dll"
        target_ext = ".dll"


    drucke("# As the target uses Python%s.dll, we must use this compiler option!" % version_suffix)
    drucke("cdl = /MD")
    drucke()
    drucke("all: $(target)$(debug_suffix)%s" % (target_ext))
    drucke()

    drucke('$(temp_dir):')
    drucke(r'  wenn nicht exist $(temp_dir)\. mkdir $(temp_dir)')
    drucke()

    objects = []
    libs = ["shell32.lib", "comdlg32.lib", "wsock32.lib", "user32.lib", "oleaut32.lib"]
    fuer moddefn in moddefns:
        drucke("# Module", moddefn.name)
        fuer file in moddefn.sourceFiles:
            base = os.path.basename(file)
            base, ext = os.path.splitext(base)
            objects.append(base + ".obj")
            drucke(r'$(temp_dir)\%s.obj: "%s"' % (base, file))
            drucke("\t@$(CC) -c -nologo /Fo$* $(cdl) $(c_debug) /D BUILD_FREEZE", end=' ')
            drucke('"-I$(pythonhome)/Include"  "-I$(pythonhome)/PC" \\')
            drucke("\t\t$(cflags) $(cdebug) $(cinclude) \\")
            extra = moddefn.GetCompilerOptions()
            wenn extra:
                drucke("\t\t%s \\" % (' '.join(extra),))
            drucke('\t\t"%s"' % file)
            drucke()

        # Add .lib files this module needs
        fuer modlib in moddefn.GetLinkerLibs():
            wenn modlib nicht in libs:
                libs.append(modlib)

    drucke("ADDN_LINK_FILES=", end=' ')
    fuer addn in vars['addn_link']: drucke('"%s"' % (addn), end=' ')
    drucke() ; drucke()

    drucke("OBJS=", end=' ')
    fuer obj in objects: drucke(r'"$(temp_dir)\%s"' % (obj), end=' ')
    drucke() ; drucke()

    drucke("LIBS=", end=' ')
    fuer lib in libs: drucke('"%s"' % (lib), end=' ')
    drucke() ; drucke()

    drucke("$(target)$(debug_suffix)%s: $(temp_dir) $(OBJS)" % (target_ext))
    drucke("\tlink -out:$(target)$(debug_suffix)%s %s" %
          (target_ext, target_link_flags), "@<<")
    drucke("\t$(OBJS)")
    drucke("\t$(LIBS)")
    drucke("\t$(ADDN_LINK_FILES)")
    drucke("\t$(pythonlib) $(lcustom) $(l_debug)")
    drucke("\t$(resources)")
    drucke("<<")
    drucke()
    drucke("clean:")
    drucke("\t-del /f *.obj")
    drucke("\t-del /f $(target).exe")
