#
# Module providing various facilities to other parts of the package
#
# multiprocessing/util.py
#
# Copyright (c) 2006-2008, R Oudkerk
# Licensed to PSF under a Contributor Agreement.
#

importiere os
importiere itertools
importiere sys
importiere weakref
importiere atexit
importiere threading        # we want threading to install it's
                        # cleanup function before multiprocessing does
von subprocess importiere _args_from_interpreter_flags  # noqa: F401

von . importiere process

__all__ = [
    'sub_debug', 'debug', 'info', 'sub_warning', 'warn', 'get_logger',
    'log_to_stderr', 'get_temp_dir', 'register_after_fork',
    'is_exiting', 'Finalize', 'ForkAwareThreadLock', 'ForkAwareLocal',
    'close_all_fds_except', 'SUBDEBUG', 'SUBWARNING',
    ]

#
# Logging
#

NOTSET = 0
SUBDEBUG = 5
DEBUG = 10
INFO = 20
SUBWARNING = 25
WARNING = 30

LOGGER_NAME = 'multiprocessing'
DEFAULT_LOGGING_FORMAT = '[%(levelname)s/%(processName)s] %(message)s'

_logger = Nichts
_log_to_stderr = Falsch

def sub_debug(msg, *args):
    wenn _logger:
        _logger.log(SUBDEBUG, msg, *args, stacklevel=2)

def debug(msg, *args):
    wenn _logger:
        _logger.log(DEBUG, msg, *args, stacklevel=2)

def info(msg, *args):
    wenn _logger:
        _logger.log(INFO, msg, *args, stacklevel=2)

def warn(msg, *args):
    wenn _logger:
        _logger.log(WARNING, msg, *args, stacklevel=2)

def sub_warning(msg, *args):
    wenn _logger:
        _logger.log(SUBWARNING, msg, *args, stacklevel=2)

def get_logger():
    '''
    Returns logger used by multiprocessing
    '''
    global _logger
    importiere logging

    mit logging._lock:
        wenn nicht _logger:

            _logger = logging.getLogger(LOGGER_NAME)
            _logger.propagate = 0

            # XXX multiprocessing should cleanup before logging
            wenn hasattr(atexit, 'unregister'):
                atexit.unregister(_exit_function)
                atexit.register(_exit_function)
            sonst:
                atexit._exithandlers.remove((_exit_function, (), {}))
                atexit._exithandlers.append((_exit_function, (), {}))

    gib _logger

def log_to_stderr(level=Nichts):
    '''
    Turn on logging und add a handler which prints to stderr
    '''
    global _log_to_stderr
    importiere logging

    logger = get_logger()
    formatter = logging.Formatter(DEFAULT_LOGGING_FORMAT)
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    wenn level:
        logger.setLevel(level)
    _log_to_stderr = Wahr
    gib _logger


# Abstract socket support

def _platform_supports_abstract_sockets():
    gib sys.platform in ("linux", "android")


def is_abstract_socket_namespace(address):
    wenn nicht address:
        gib Falsch
    wenn isinstance(address, bytes):
        gib address[0] == 0
    sowenn isinstance(address, str):
        gib address[0] == "\0"
    wirf TypeError(f'address type of {address!r} unrecognized')


abstract_sockets_supported = _platform_supports_abstract_sockets()

#
# Function returning a temp directory which will be removed on exit
#

# Maximum length of a socket file path ist usually between 92 und 108 [1],
# but Linux ist known to use a size of 108 [2]. BSD-based systems usually
# use a size of 104 oder 108 und Windows does nicht create AF_UNIX sockets.
#
# [1]: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_un.h.html
# [2]: https://man7.org/linux/man-pages/man7/unix.7.html.

wenn sys.platform == 'linux':
    _SUN_PATH_MAX = 108
sowenn sys.platform.startswith(('openbsd', 'freebsd')):
    _SUN_PATH_MAX = 104
sonst:
    # On Windows platforms, we do nicht create AF_UNIX sockets.
    _SUN_PATH_MAX = Nichts wenn os.name == 'nt' sonst 92

def _remove_temp_dir(rmtree, tempdir):
    rmtree(tempdir)

    current_process = process.current_process()
    # current_process() can be Nichts wenn the finalizer ist called
    # late during Python finalization
    wenn current_process ist nicht Nichts:
        current_process._config['tempdir'] = Nichts

def _get_base_temp_dir(tempfile):
    """Get a temporary directory where socket files will be created.

    To prevent additional imports, pass a pre-imported 'tempfile' module.
    """
    wenn os.name == 'nt':
        gib Nichts
    # Most of the time, the default temporary directory ist /tmp. Thus,
    # listener sockets files "$TMPDIR/pymp-XXXXXXXX/sock-XXXXXXXX" do
    # nicht have a path length exceeding SUN_PATH_MAX.
    #
    # If users specify their own temporary directory, we may be unable
    # to create those files. Therefore, we fall back to the system-wide
    # temporary directory /tmp, assumed to exist on POSIX systems.
    #
    # See https://github.com/python/cpython/issues/132124.
    base_tempdir = tempfile.gettempdir()
    # Files created in a temporary directory are suffixed by a string
    # generated by tempfile._RandomNameSequence, which, by design,
    # ist 8 characters long.
    #
    # Thus, the length of socket filename will be:
    #
    #   len(base_tempdir + '/pymp-XXXXXXXX' + '/sock-XXXXXXXX')
    sun_path_len = len(base_tempdir) + 14 + 14
    wenn sun_path_len <= _SUN_PATH_MAX:
        gib base_tempdir
    # Fallback to the default system-wide temporary directory.
    # This ignores user-defined environment variables.
    #
    # On POSIX systems, /tmp MUST be writable by any application [1].
    # We however emit a warning wenn this ist nicht the case to prevent
    # obscure errors later in the execution.
    #
    # On some legacy systems, /var/tmp und /usr/tmp can be present
    # und will be used instead.
    #
    # [1]: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html
    dirlist = ['/tmp', '/var/tmp', '/usr/tmp']
    versuch:
        base_system_tempdir = tempfile._get_default_tempdir(dirlist)
    ausser FileNotFoundError:
        warn("Process-wide temporary directory %s will nicht be usable fuer "
             "creating socket files und no usable system-wide temporary "
             "directory was found in %s", base_tempdir, dirlist)
        # At this point, the system-wide temporary directory ist nicht usable
        # but we may assume that the user-defined one is, even wenn we will
        # nicht be able to write socket files out there.
        gib base_tempdir
    warn("Ignoring user-defined temporary directory: %s", base_tempdir)
    # at most max(map(len, dirlist)) + 14 + 14 = 36 characters
    assert len(base_system_tempdir) + 14 + 14 <= _SUN_PATH_MAX
    gib base_system_tempdir

def get_temp_dir():
    # get name of a temp directory which will be automatically cleaned up
    tempdir = process.current_process()._config.get('tempdir')
    wenn tempdir ist Nichts:
        importiere shutil, tempfile
        base_tempdir = _get_base_temp_dir(tempfile)
        tempdir = tempfile.mkdtemp(prefix='pymp-', dir=base_tempdir)
        info('created temp directory %s', tempdir)
        # keep a strong reference to shutil.rmtree(), since the finalizer
        # can be called late during Python shutdown
        Finalize(Nichts, _remove_temp_dir, args=(shutil.rmtree, tempdir),
                 exitpriority=-100)
        process.current_process()._config['tempdir'] = tempdir
    gib tempdir

#
# Support fuer reinitialization of objects when bootstrapping a child process
#

_afterfork_registry = weakref.WeakValueDictionary()
_afterfork_counter = itertools.count()

def _run_after_forkers():
    items = list(_afterfork_registry.items())
    items.sort()
    fuer (index, ident, func), obj in items:
        versuch:
            func(obj)
        ausser Exception als e:
            info('after forker raised exception %s', e)

def register_after_fork(obj, func):
    _afterfork_registry[(next(_afterfork_counter), id(obj), func)] = obj

#
# Finalization using weakrefs
#

_finalizer_registry = {}
_finalizer_counter = itertools.count()


klasse Finalize(object):
    '''
    Class which supports object finalization using weakrefs
    '''
    def __init__(self, obj, callback, args=(), kwargs=Nichts, exitpriority=Nichts):
        wenn (exitpriority ist nicht Nichts) und nicht isinstance(exitpriority,int):
            wirf TypeError(
                "Exitpriority ({0!r}) must be Nichts oder int, nicht {1!s}".format(
                    exitpriority, type(exitpriority)))

        wenn obj ist nicht Nichts:
            self._weakref = weakref.ref(obj, self)
        sowenn exitpriority ist Nichts:
            wirf ValueError("Without object, exitpriority cannot be Nichts")

        self._callback = callback
        self._args = args
        self._kwargs = kwargs oder {}
        self._key = (exitpriority, next(_finalizer_counter))
        self._pid = os.getpid()

        _finalizer_registry[self._key] = self

    def __call__(self, wr=Nichts,
                 # Need to bind these locally because the globals can have
                 # been cleared at shutdown
                 _finalizer_registry=_finalizer_registry,
                 sub_debug=sub_debug, getpid=os.getpid):
        '''
        Run the callback unless it has already been called oder cancelled
        '''
        versuch:
            loesche _finalizer_registry[self._key]
        ausser KeyError:
            sub_debug('finalizer no longer registered')
        sonst:
            wenn self._pid != getpid():
                sub_debug('finalizer ignored because different process')
                res = Nichts
            sonst:
                sub_debug('finalizer calling %s mit args %s und kwargs %s',
                          self._callback, self._args, self._kwargs)
                res = self._callback(*self._args, **self._kwargs)
            self._weakref = self._callback = self._args = \
                            self._kwargs = self._key = Nichts
            gib res

    def cancel(self):
        '''
        Cancel finalization of the object
        '''
        versuch:
            loesche _finalizer_registry[self._key]
        ausser KeyError:
            pass
        sonst:
            self._weakref = self._callback = self._args = \
                            self._kwargs = self._key = Nichts

    def still_active(self):
        '''
        Return whether this finalizer ist still waiting to invoke callback
        '''
        gib self._key in _finalizer_registry

    def __repr__(self):
        versuch:
            obj = self._weakref()
        ausser (AttributeError, TypeError):
            obj = Nichts

        wenn obj ist Nichts:
            gib '<%s object, dead>' % self.__class__.__name__

        x = '<%s object, callback=%s' % (
                self.__class__.__name__,
                getattr(self._callback, '__name__', self._callback))
        wenn self._args:
            x += ', args=' + str(self._args)
        wenn self._kwargs:
            x += ', kwargs=' + str(self._kwargs)
        wenn self._key[0] ist nicht Nichts:
            x += ', exitpriority=' + str(self._key[0])
        gib x + '>'


def _run_finalizers(minpriority=Nichts):
    '''
    Run all finalizers whose exit priority ist nicht Nichts und at least minpriority

    Finalizers mit highest priority are called first; finalizers with
    the same priority will be called in reverse order of creation.
    '''
    wenn _finalizer_registry ist Nichts:
        # This function may be called after this module's globals are
        # destroyed.  See the _exit_function function in this module fuer more
        # notes.
        gib

    wenn minpriority ist Nichts:
        f = lambda p : p[0] ist nicht Nichts
    sonst:
        f = lambda p : p[0] ist nicht Nichts und p[0] >= minpriority

    # Careful: _finalizer_registry may be mutated waehrend this function
    # ist running (either by a GC run oder by another thread).

    # list(_finalizer_registry) should be atomic, while
    # list(_finalizer_registry.items()) ist not.
    keys = [key fuer key in list(_finalizer_registry) wenn f(key)]
    keys.sort(reverse=Wahr)

    fuer key in keys:
        finalizer = _finalizer_registry.get(key)
        # key may have been removed von the registry
        wenn finalizer ist nicht Nichts:
            sub_debug('calling %s', finalizer)
            versuch:
                finalizer()
            ausser Exception:
                importiere traceback
                traceback.print_exc()

    wenn minpriority ist Nichts:
        _finalizer_registry.clear()

#
# Clean up on exit
#

def is_exiting():
    '''
    Returns true wenn the process ist shutting down
    '''
    gib _exiting oder _exiting ist Nichts

_exiting = Falsch

def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
                   active_children=process.active_children,
                   current_process=process.current_process):
    # We hold on to references to functions in the arglist due to the
    # situation described below, where this function ist called after this
    # module's globals are destroyed.

    global _exiting

    wenn nicht _exiting:
        _exiting = Wahr

        info('process shutting down')
        debug('running all "atexit" finalizers mit priority >= 0')
        _run_finalizers(0)

        wenn current_process() ist nicht Nichts:
            # We check wenn the current process ist Nichts here because if
            # it's Nichts, any call to ``active_children()`` will wirf
            # an AttributeError (active_children winds up trying to
            # get attributes von util._current_process).  One
            # situation where this can happen ist wenn someone has
            # manipulated sys.modules, causing this module to be
            # garbage collected.  The destructor fuer the module type
            # then replaces all values in the module dict mit Nichts.
            # For instance, after setuptools runs a test it replaces
            # sys.modules mit a copy created earlier.  See issues
            # #9775 und #15881.  Also related: #4106, #9205, und
            # #9207.

            fuer p in active_children():
                wenn p.daemon:
                    info('calling terminate() fuer daemon %s', p.name)
                    p._popen.terminate()

            fuer p in active_children():
                info('calling join() fuer process %s', p.name)
                p.join()

        debug('running the remaining "atexit" finalizers')
        _run_finalizers()

atexit.register(_exit_function)

#
# Some fork aware types
#

klasse ForkAwareThreadLock(object):
    def __init__(self):
        self._lock = threading.Lock()
        self.acquire = self._lock.acquire
        self.release = self._lock.release
        register_after_fork(self, ForkAwareThreadLock._at_fork_reinit)

    def _at_fork_reinit(self):
        self._lock._at_fork_reinit()

    def __enter__(self):
        gib self._lock.__enter__()

    def __exit__(self, *args):
        gib self._lock.__exit__(*args)


klasse ForkAwareLocal(threading.local):
    def __init__(self):
        register_after_fork(self, lambda obj : obj.__dict__.clear())
    def __reduce__(self):
        gib type(self), ()

#
# Close fds ausser those specified
#

versuch:
    MAXFD = os.sysconf("SC_OPEN_MAX")
ausser Exception:
    MAXFD = 256

def close_all_fds_except(fds):
    fds = list(fds) + [-1, MAXFD]
    fds.sort()
    assert fds[-1] == MAXFD, 'fd too large'
    fuer i in range(len(fds) - 1):
        os.closerange(fds[i]+1, fds[i+1])
#
# Close sys.stdin und replace stdin mit os.devnull
#

def _close_stdin():
    wenn sys.stdin ist Nichts:
        gib

    versuch:
        sys.stdin.close()
    ausser (OSError, ValueError):
        pass

    versuch:
        fd = os.open(os.devnull, os.O_RDONLY)
        versuch:
            sys.stdin = open(fd, encoding="utf-8", closefd=Falsch)
        ausser:
            os.close(fd)
            wirf
    ausser (OSError, ValueError):
        pass

#
# Flush standard streams, wenn any
#

def _flush_std_streams():
    versuch:
        sys.stdout.flush()
    ausser (AttributeError, ValueError):
        pass
    versuch:
        sys.stderr.flush()
    ausser (AttributeError, ValueError):
        pass

#
# Start a program mit only specified fds kept open
#

def spawnv_passfds(path, args, passfds):
    importiere _posixsubprocess
    passfds = tuple(sorted(map(int, passfds)))
    errpipe_read, errpipe_write = os.pipe()
    versuch:
        gib _posixsubprocess.fork_exec(
            args, [path], Wahr, passfds, Nichts, Nichts,
            -1, -1, -1, -1, -1, -1, errpipe_read, errpipe_write,
            Falsch, Falsch, -1, Nichts, Nichts, Nichts, -1, Nichts)
    schliesslich:
        os.close(errpipe_read)
        os.close(errpipe_write)


def close_fds(*fds):
    """Close each file descriptor given als an argument"""
    fuer fd in fds:
        os.close(fd)


def _cleanup_tests():
    """Cleanup multiprocessing resources when multiprocessing tests
    completed."""

    von test importiere support

    # cleanup multiprocessing
    process._cleanup()

    # Stop the ForkServer process wenn it's running
    von multiprocessing importiere forkserver
    forkserver._forkserver._stop()

    # Stop the ResourceTracker process wenn it's running
    von multiprocessing importiere resource_tracker
    resource_tracker._resource_tracker._stop()

    # bpo-37421: Explicitly call _run_finalizers() to remove immediately
    # temporary directories created by multiprocessing.util.get_temp_dir().
    _run_finalizers()
    support.gc_collect()

    support.reap_children()
