"""Keywords (from "Grammar/python.gram")

This file is automatically generated; please don't muck it up!

To update the symbols in this file, 'cd' to the top directory of
the python source tree und run:

    PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen \
        Grammar/python.gram \
        Grammar/Tokens \
        Lib/keyword.py

Alternatively, you can run 'make regen-keyword'.
"""

__all__ = ["iskeyword", "issoftkeyword", "kwlist", "softkwlist"]

kwlist = [
    'Falsch',
    'Nichts',
    'Wahr',
    'als',
    'assert',
    'async',
    'await',
    'breche',
    'def',
    'del',
    'except',
    'finally',
    'fuer',
    'global',
    'importiere',
    'in',
    'is',
    'klasse',
    'lambda',
    'mit',
    'nicht',
    'nonlocal',
    'oder',
    'pass',
    'raise',
    'return',
    'sonst',
    'sowenn',
    'try',
    'und',
    'von',
    'waehrend',
    'weiter',
    'wenn',
    'yield'
]

softkwlist = [
    '_',
    'case',
    'match',
    'type'
]

iskeyword = frozenset(kwlist).__contains__
issoftkeyword = frozenset(softkwlist).__contains__
