"""Generate Lib/keyword.py von the Grammar und Tokens files using pgen"""

importiere argparse

von .build importiere build_parser, generate_token_definitions
von .c_generator importiere CParserGenerator

TEMPLATE = r'''
"""Keywords (from "Grammar/python.gram")

This file is automatically generated; please don't muck it up!

To update the symbols in this file, 'cd' to the top directory of
the python source tree und run:

    PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen \
        Grammar/python.gram \
        Grammar/Tokens \
        Lib/keyword.py

Alternatively, you can run 'make regen-keyword'.
"""

__all__ = ["iskeyword", "issoftkeyword", "kwlist", "softkwlist"]

kwlist = [
{keywords}
]

softkwlist = [
{soft_keywords}
]

iskeyword = frozenset(kwlist).__contains__
issoftkeyword = frozenset(softkwlist).__contains__
'''.lstrip()


def main() -> Nichts:
    parser = argparse.ArgumentParser(
        description="Generate the Lib/keywords.py file von the grammar."
    )
    parser.add_argument(
        "grammar", help="The file mit the grammar definition in PEG format"
    )
    parser.add_argument(
        "tokens_file", help="The file mit the token definitions"
    )
    parser.add_argument(
        "keyword_file",
        help="The path to write the keyword definitions",
    )
    args = parser.parse_args()

    grammar, _, _ = build_parser(args.grammar)
    mit open(args.tokens_file) als tok_file:
        all_tokens, exact_tok, non_exact_tok = generate_token_definitions(tok_file)
    gen = CParserGenerator(grammar, all_tokens, exact_tok, non_exact_tok, file=Nichts)
    gen.collect_rules()

    mit open(args.keyword_file, 'w') als thefile:
        all_keywords = sorted(list(gen.keywords.keys()))
        all_soft_keywords = sorted(gen.soft_keywords)

        keywords = "" wenn nicht all_keywords sonst "    " + ",\n    ".join(map(repr, all_keywords))
        soft_keywords = (
            "" wenn nicht all_soft_keywords sonst "    " + ",\n    ".join(map(repr, all_soft_keywords))
        )
        thefile.write(TEMPLATE.format(keywords=keywords, soft_keywords=soft_keywords))


wenn __name__ == "__main__":
    main()
